#Calvin Low
#Shows discounts of a clearance item spread throughout 4 weeks based on percent discounts listen below
print("Welcome to our clothing store, we have lots of clearance items on sale today!")
print()
print("Clearence items are discounted as follows:")
print("Week 1 - 20% off, Week 2 - 25% off, week 3 - 30% off, Week 4 - 50% off")
print()
print("Please keep in mind that all discounts after week 1 corresponds to the new price that they were discounted to previously")
print()
price = float(input("Please enter a price and we'll show you how much its discounted thoughout the week!"))
week_1 = price - price * float(.20)
week_2 = week_1 - week_1 * float(.25)
week_3 = week_2 - week_2 * float(.30)
week_4 = week_3 - week_3 * float(.50)
print()
print("Okay, your discounts is as follows:")
print("The intial price was", "$"+str(price))
print("Week 1 is", "$"+str(week_1)) 
print("Week 2 is", "$"+str(week_2))
print("Week 3 is", "$"+str(week_3))
print("Week 4 is", "$"+str(week_4))
print()
print("Thank you for shopping with us!")
input('Press ENTER to exit')